[project]
name = "WLS-SVM"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.3",
    "scipy>=1.16.1",
    "torch>=2.8.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.uv]
package = true
